# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = TrendDBCalc
DESTDIR = ../x64/Debug
CONFIG += debug
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
HEADERS += ./stdafx.h \
    ./TrendDBCalc.h
SOURCES += ./TrendDBCalc.cpp \
    ./main.cpp \
    ./stdafx.cpp
FORMS += ./TrendDBCalc.ui
RESOURCES += TrendDBCalc.qrc
